### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by bluedayday** [megagao/production_ssm#1]
数据库文件没找到？

**Comment by megagao** [comment]
给我发邮件，我邮件发给你，谢谢。

**Comment by liwei0903nn** [comment]
请问能上传下  数据库 文件吗？

**Comment by megagao** [comment]
给我发邮件，我邮件发给你，谢谢。

**Comment by fanqieo** [comment]
额麻烦发个邮件给我没有SQL文件哦547888822@qq.com

**Comment by borners** [comment]
请问数据库能发一下嘛

**Comment by megagao** [comment]
@borners 留个邮箱，我发给你

**Comment by liwei0903nn** [comment]
1137110730@qq.com  谢谢了

**Comment by zyylhg** [comment]
请问数据库能发一下嘛,1057703577@qq.com 谢谢了

**Comment by Descto** [comment]
请问能发份数据库给我吗？usckur@gmail.com 谢谢

**Comment by walker0819** [comment]
您好，数据库脚本能发一下吗？751737642@qq.com

**Comment by JumpAlang** [comment]
正要研究，能发份数据库脚本给我吗？1040927107@qq.com

**Comment by xiongyouhua** [comment]
您好，数据库脚本能发一下吗？815511406@qq.com

**Comment by lingya** [comment]
您好，数据库脚本能发一下吗？

**Comment by lingya** [comment]
您好，数据库脚本能发一下吗？ 1617229094@qq.com

**Comment by hangxtx** [comment]
需要您的数据库文件，先谢谢啦 444313896@qq.com

**Comment by wingbillow** [comment]
需要您的数据库文件，先谢谢啦 283157287@qq.com

**Comment by hellboypxl** [comment]
想研究一下，请发给我数据库文件，谢谢了 wisewin1985@163.com

**Comment by SaberSola** [comment]
需要您的数据库脚本可以发下么 谢谢1198902364@qq.com

**Comment by 1737255535** [comment]
想研究一下，请发给我数据库文件,邮箱1737255535@qq.com，谢谢了

**Comment by yzzs** [comment]
想学习下，请发数据库脚本给我邮箱yzzs276@163.com,谢谢！

**Comment by xuantian001** [comment]
想研究一下，请发给我数据库文件,邮箱wanluan20317@qq.com，谢谢了!

**Comment by sylencer** [comment]
您好，数据库文件能发下吗，邮箱436064546@qq.com，万分感谢！

**Comment by geekZeroLi** [comment]
您好，数据库文件能发下吗，邮箱18363998152@163.com，万分感谢！

**Comment by spearLeaf** [comment]
您好，数据库文件能发给我么，万分感谢，正在学习中，邮箱493152738@qq.com

**Comment by hellojuny** [comment]
您好，能发个数据库文件么，zl6610@icloud.com，感谢🙏

**Comment by mashiqiong** [comment]
您好，能发个数据库文件么，万分感谢，正在学习中，1755335793@qq.com，感谢

**Comment by lisqiCSDN** [comment]
您好，能发个数据库文件么，现在正在开发ERP系统，1499414047@qq.com，感谢

**Comment by DevStarChina** [comment]
您好，数据库文件能发下吗，邮箱 781047852@qq.com，万分感谢！

**Comment by fyq88013420** [comment]
兄弟，能发一下数据库吗,498385706@qq.com 谢谢了

**Comment by lockbur** [comment]
给我也发一下 845885222@qq.com 谢谢

**Comment by wanggdme** [comment]
你好，能发一下数据库脚本吗，我的邮箱2381717192@qq.com ，非常感谢

**Comment by xinyouqingxi** [comment]
能发一下数据库文件吗：lusalome@163.com

**Comment by xingkong1** [comment]
你好，能发一下数据库脚本吗，我的邮箱1727314512@qq.com ，非常感谢...

**Comment by LionCoder4ever** [comment]
你好,项目很好,已star,能给我一份数据库文件吗,不胜感激,我的邮箱kzwcoder2015@163.com

**Comment by hachiko02** [comment]
能发下sql文件吗(745922085@qq.com)……正想学习学习,谢谢

**Comment by xtpy1234** [comment]
能发下数据库文件吗？xtpy_12@163.com

**Comment by xixi0521** [comment]
您好，请问可以发一下数据库文件吗？项目很赞，万分感谢~~778274692@qq.com，，谢谢...

**Comment by makun1989** [comment]
能发份数据库文件吗?项目很好,想好好学习下:mma_kun@163.com,万分感谢

**Comment by oomeD** [comment]
能发下数据库文件吗？2187733138@qq.com，谢谢！

**Comment by hongzhunzhou** [comment]
1161122599@qq.com
<br/> thanks

**Comment by aftereclipse** [comment]
数据库文件有吗，aftereclipse@163.com

**Comment by aftereclipse** [comment]
感觉@ResponseBody直接返回JSONObject 比较灵活，比返回Map<String,Object>更灵活，JSON库用net.sf.json或者fastjson都行，不过fastjson有漏洞，最好用最新版

**Comment by GitHubSupervise** [comment]
能分享下sql文件吗，1025142302@qq.com
Thanks

**Comment by aftereclipse** [comment]
发我的indoor_pos.sql和production_ssm项目不对应，应该不是这个项目的数据库文件，还请大神重发一个

**Comment by miaosha300** [comment]
麻烦分享下sql文件，17712409306@163.com，谢谢！

**Comment by megagao** [comment]
@aftereclipse 不好意思，刚重新给你发了

**Comment by zouchengli** [comment]
给个sql脚本谢谢,chengli.zou@gmail.com
