### ISSUE TITLE
部署之后如何访问

### ISSUE THREAD

**Issue by zhaohaibo123** [megagao/production_ssm#10]
IDEA倒入项目 部署到tomcat中控制台错误如下
22-Sep-2017 11:45:57.759 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\apache-tomcat-8.5.20\webapps\examples] has finished in [621] ms
22-Sep-2017 11:45:57.760 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\apache-tomcat-8.5.20\webapps\host-manager]
22-Sep-2017 11:45:57.804 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\apache-tomcat-8.5.20\webapps\host-manager] has finished in [44] ms
22-Sep-2017 11:45:57.805 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\apache-tomcat-8.5.20\webapps\manager]
22-Sep-2017 11:45:57.844 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\apache-tomcat-8.5.20\webapps\manager] has finished in [40] ms
22-Sep-2017 11:45:57.865 严重 [RMI TCP Connection(7)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
22-Sep-2017 11:45:57.866 严重 [RMI TCP Connection(7)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2017-09-22 11:45:57,958] Artifact production_ms:war: Error during artifact deployment. See server log for details.

请问这是什么错 
请我我如何访问 http://localhost:8080/ 这样访问不行

**Comment by megagao** [comment]
@zhaohaibo123 看你设置的context是什么了，eclipse下默认是/prodution_ms
