### ISSUE TITLE
启动tomcat报错

### ISSUE THREAD

**Issue by cGitHub123** [megagao/production_ssm#17]
Could not resolve bean definition resource pattern [classpath:spring/applicationContext-*.xml]; nested exception is java.io.FileNotFoundException: class path resource [spring/] cannot be resolved to URL because it does not exist

**Comment by megagao** [comment]
看下文档里面的idea class配置那里的方法能否解决

**Comment by megagao** [comment]
@cGitHub123 看下文档里面的idea class配置那里的方法能否解决

**Comment by cGitHub123** [comment]
谢谢你的回复，可我用的是eclipse哎

**Comment by cGitHub123** [comment]
发现了，是pom那里路径少个S

**Comment by megagao** [comment]
@cGitHub123 发个pull request吧
