### ISSUE TITLE
你好，有个图片不显示的问题

### ISSUE THREAD

**Issue by llkoio** [megagao/production_ssm#19]
你好
产品管理，上传了图片，在产品编辑页面里不显示
tomcat的server.xml配置了pic的context

**Comment by llkoio** [comment]
上传成功了
D盘的img文件夹里也有图片文件
但是前端的<img src="/pic/1529233470518430.jpg" class="ke-img" data-status="-4" width="80" height="80" alt="85.jpg">却访问不到图片
tomcat的server.xml配置了pic的context

**Comment by llkoio** [comment]
但是前端的《img src="/pic/1529233470518430.jpg" class="ke-img" data-status="-4" width="80" height="80" alt="85.jpg"》却访问不到图片

**Comment by Shuaidezixin** [comment]
前端和后端是在同一个应用吗，




| |
tan si jun
邮箱：15821060241@163.com
|

签名由 网易邮箱大师 定制

在2018年06月17日 19:10，llkoio 写道：

但是前端的《img src="/pic/1529233470518430.jpg" class="ke-img" data-status="-4" width="80" height="80" alt="85.jpg"》却访问不到图片

**Comment by llkoio** [comment]
在idea中配置tomcat的时候没有勾选”Deploy applications configured in tomact instance“
导致不能识别host下配置的context
谢谢你的回复
