### ISSUE TITLE
请问图片无法正常显示的这个配置链接404，能否重发一下呢

### ISSUE THREAD

**Issue by Fhourn** [megagao/production_ssm#30]

**Comment by lulb** [comment]
个人测试没有任何问题，一般出现问题是数据库是否配置成功








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fhourn"<notifications@github.com&gt;; 
发送时间: 2019年12月30日(星期一) 下午5:42
收件人: "megagao/production_ssm"<production_ssm@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30)

**Comment by Fhourn** [comment]
> 个人测试没有任何问题，一般出现问题是数据库是否配置成功
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fhourn"<notifications@github.com&gt;; 发送时间: 2019年12月30日(星期一) 下午5:42 收件人: "megagao/production_ssm"<production_ssm@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Fhourn** [comment]
> 个人测试没有任何问题，一般出现问题是数据库是否配置成功
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fhourn"<notifications@github.com&gt;; 发送时间: 2019年12月30日(星期一) 下午5:42 收件人: "megagao/production_ssm"<production_ssm@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

数据库没问题，图片可以上传删除，但是就是页面不显示，点图片报404，可是我这个路径有图片的，或许你知道这是什么原因吗

**Comment by Shuaidezixin** [comment]
静态资源目录没有配置映射访问权限




| |
tan si jun
邮箱：15821060241@163.com
|

Signature is customized by Netease Mail Master

在2019年12月30日 18:30，Fhourn 写道：

个人测试没有任何问题，一般出现问题是数据库是否配置成功
…
------------------ 原始邮件 ------------------ 发件人: "Fhourn"<notifications@github.com>; 发送时间: 2019年12月30日(星期一) 下午5:42 收件人: "megagao/production_ssm"<production_ssm@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

数据库没问题，图片可以上传删除，但是就是页面不显示，点图片报404，可是我这个路径有图片的，或许你知道这是什么原因吗

**Comment by Fhourn** [comment]
> 静态资源目录没有配置映射访问权限 | | tan si jun 邮箱：15821060241@163.com | Signature is customized by Netease Mail Master 在2019年12月30日 18:30，Fhourn 写道： 个人测试没有任何问题，一般出现问题是数据库是否配置成功 … ------------------ 原始邮件 ------------------ 发件人: "Fhourn"<notifications@github.com>; 发送时间: 2019年12月30日(星期一) 下午5:42 收件人: "megagao/production_ssm"<production_ssm@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 数据库没问题，图片可以上传删除，但是就是页面不显示，点图片报404，可是我这个路径有图片的，或许你知道这是什么原因吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

或许您方便吗，可以再仔细讲讲需要改哪里吗，我改的都没效果

**Comment by Fhourn** [comment]
> 静态资源目录没有配置映射访问权限 | | tan si jun 邮箱：15821060241@163.com | Signature is customized by Netease Mail Master 在2019年12月30日 18:30，Fhourn 写道： 个人测试没有任何问题，一般出现问题是数据库是否配置成功 … ------------------ 原始邮件 ------------------ 发件人: "Fhourn"<notifications@github.com>; 发送时间: 2019年12月30日(星期一) 下午5:42 收件人: "megagao/production_ssm"<production_ssm@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [megagao/production_ssm] 请问图片无法正常显示的这个配置链接404，能否重发一下呢 (#30) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 数据库没问题，图片可以上传删除，但是就是页面不显示，点图片报404，可是我这个路径有图片的，或许你知道这是什么原因吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢回复，回显问题，调整好了
