### ISSUE TITLE
现在这个展示的链接失效了吗？访问不了了

### ISSUE THREAD

**Issue by neil88** [megagao/production_ssm#31]
http://www.realfond.cn/2016/12/27/%E7%94%9F%E4%BA%A7%E7%AE%A1%E7%90%86ERP%E7%B3%BB%E7%BB%9F/

404 - 找不到文件或目录。
您要查找的资源可能已被删除，已更改名称或者暂时不可用。

**Comment by megagao** [comment]
忘了续费了，失效了。。
