### ISSUE TITLE
项目好像有ＢＵＧ啊，我用物料管理员账号登录系统

### ISSUE THREAD

**Issue by cesarewang** [megagao/production_ssm#5]
如题，我用物料管理员登录系统，登录完这个用户还可以进行设备管理等各种功能，但是在角色权限配置那个地方是没有这些权限的，能修复一下么～大神

**Comment by megagao** [comment]
@cesarewang 我这边没有出现这个问题啊，我用55，55账号登录，也就是物料管理员，但是没出现你说的能操作设备这个问题，你再试试，或者发详细的给我邮箱，谢谢。

**Comment by cesarewang** [comment]
嗯，问题是这样的：
1、用物料管理员登录，确实不能修改设备数据，但是能看到设备数据，我看数据库里面菜单是有配置的，但是在前端没有控制展示逻辑（只有系统管理这个菜单有控制展示逻辑）。
2、用户session过期后，点击一个新的功能页面，不会默认跳到登录页面，只是看不到那几个增删改查的按钮了（给用户的感知特别像BUG啊），只有刷新页面才会跳到登录页面。
项目写的挺好的，谢谢。

**Comment by megagao** [comment]
@cesarewang 
1、关于设备管理等没有像系统管理那样在前端进行显示控制，这是我们的需求，就是普通用户也可以查看这些信息，但是没有相应的维护权限，如果你的需求不是这样的，可以做相应的更改
2、session过期确实还没做跳转登录，最近有点忙，没时间改，我会尽快的。当然，你也可以改改给我发pull request

**Comment by megagao** [comment]
@cesarewang 你好，端午假期有空，session过期跳转登录我已经实现了，有兴趣可以下载最新的。

**Comment by cesarewang** [comment]
谢谢  我研究一下。
